### ISSUE TITLE
BUILD ERROR

### ISSUE THREAD

**Issue by greenybignose** [tronprotocol/java-tron#1012]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I try to Build -> Build project for java-tron project using intellij idea. But, so many error, some is logger and another error happen too. 

2. What did you expect to see?

BUILD SUCCESSFULL

3. What did you see instead?

<img width="960" alt="error" src="https://user-images.githubusercontent.com/40190529/41419169-8d7a4fa6-701b-11e8-996c-fb98fe2dfbe5.png">

**Comment by kookiekrak** [comment]
Hi @greenybignose, can you expand one of those errors so we can see what it's failing to compile?

Also, if you haven't already, can you turn on "Annotation Processing" in the preferences? I've seen similar compile issues because of that.

![screen shot 2018-06-14 at 11 45 31 am](https://user-images.githubusercontent.com/585120/41431632-7adff01a-6fc8-11e8-8124-eb51a496b3d4.png)

**Comment by greenybignose** [comment]
@kookiekrak 

Error still alot even after enabling Annotation Processor. Please help. 

Thanks

**Comment by Rovak** [comment]
The errors are related to missing generated protobuf classes which happens if you aren't using gradle to run the project. Try running the project with the gradle `run` command. Or `./gradlew run`

See https://github.com/tronprotocol/java-tron#running-a-full-node for further instructions on how to run a node.

**Comment by kookiekrak** [comment]
@greenybignose The IntelliJ step is a bit outdated. You'll still need to run ./gradlew build because that'll build the missing files you currently see in IntelliJ.

You just need to run it once
