### ISSUE TITLE
This automatic tests are not automatic

### ISSUE THREAD

**Issue by abarranco** [tronprotocol/java-tron#119]
https://github.com/tronprotocol/java-tron/blob/7615871e4bfaace69b1f5f04b36d3813bbe240b3/src/test/java/org/tron/core/BlockchainTest.java#L61

What's te point on logging something in the console ¿?¿? Nobody are gonna see it, and the test is not going to fail, so you can make a new version even if the version has any bugs on it.

The test must always follow the pattern, // GIVEN // WHEN  // THEN

You need to assert things like:
assertNotNull(blockchain.getLastHash());

That is automatic, that will fail if hash is null, and you won't be able to make a new version with that bug.

If the hash must start with "000" for example you need to assert that.

This applies to 9x% of the testing code u guys have here. You need to re-do this tests. I am a java developer myself, and i was a tron holder until i saw this code. You can't refactor things with this tests, you can't improve the code with security. You need better tests and you need it for yesterday.

**Comment by HaoqiZhao** [comment]
Thank you for your effort and contribution.
Actually we are aware of the problem you mentioned here.  Although we fully agree the importance of tests, we do have lots of tasks with higher priority. Right now the whole team are focusing on other modules 100% effort. The test part is on schedule and we will definitely finish it ASAP. Our team keeps expanding and the developing speed will increase in no time.
Please do come back and check TRON's progress.
Again thank you for paying attention to project TRON. We value your opinions and appreciate your help.
Happy Chinese new year~

**Comment by seanrobbins** [comment]
FWIW I'm seeing what I can do with this with BlockchainTest specifically, as an contributor when I have time (so not been able to get a PR together as fast as I'd like because of my day job). 
It's trickier than most who haven't spent time investigating the problem would likely realise, as controlling the state of an immutable blockchain, which as a series of transactions is dependent on previous states, it is a hard testing problem. I might have something working though...

> The test must always follow the pattern, // GIVEN // WHEN // THEN

This refers to a practice called BDD (behaviour driven development), which I personally am very familiar with. Frankly, 'test must always follow' is something I'd dispute and just adding the given/when/then syntax as comments in a JUnit test, I would actually argue is an anti-pattern. If as a community we wanted to incorporate this testing style, I'd argue for a library which supports this - perhaps something like CucumberJVM.

That said, the domain is complex enough that breaking tests up into easier to understand explanations may be of some value consider:

Given a transaction which has been spent
When findUtxo is called to find unspent transactions
Then the spent transaction is not included in the result

If wanted to use a BDD tool in the project, I can prepare an example PR to see what it looks like, if wanted. Maybe open a separate ticket for trying out a BDD testing approach if that's something we want to do.

**Comment by zhaohong** [comment]
hi , @seanrobbins  Bdd sounds good to me .  Let's try it.

**Comment by Rovak** [comment]
The concerns as given by @abarranco have been fixed in the `develop` branch. I could only find 2 tests of the 135 tests which were only logging and they will be fixed shortly.

Feel free to reopen this issue if there are any other tests that need attention, or open a new issue.
