### ISSUE TITLE
Run SolidityNode and FullNode on the same host, SolidityNode http port wasn't accessible.

### ISSUE THREAD

**Issue by nodepaladin** [tronprotocol/java-tron#1223]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Hi
I'm trying to run FullNode and SolidityNode on the same host,and I do that as [https://github.com/TRONprotocol/Documentation/blob/master/TRX/Solidity_and_Full_Node_Deployment_EN.md](https://github.com/TRONprotocol/Documentation/blob/master/TRX/Solidity_and_Full_Node_Deployment_EN.md) .

2. What did you expect to see?
I want to access the SolidityNode http service on port 8091  as [https://github.com/tronprotocol/Documentation/blob/master/TRX/Tron-http.md](https://github.com/tronprotocol/Documentation/blob/master/TRX/Tron-http.md) ,pls give me a hand

3. What did you see instead?
But an error occured when I start SolidityNode after starting FullNode:
`
ERROR [main] [general](DefaultConfig.java:30) Uncaught exception
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.tron.core.db2.core.SnapshotManager] is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:372)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:332)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1057)
	at org.tron.program.SolidityNode.main(SolidityNode.java:180)
`
then I could access the port 8090, but the port 8091(SolidityNode http port) is not accessible.
Here are my configs:
### SolidityNode config:
`
node {
        trustNode = "127.0.0.1:50051"
        listen.port = 18889 // This needs to be changed.
    }
    rpc {
      port = 50052
    }
`

**Comment by kookiekrak** [comment]
@nodepaladin can you use these deployment scripts instead
https://github.com/tronprotocol/TronDeployment

**Comment by saijohnjersy** [comment]
thank you for your questions

**Comment by maks115015** [comment]
I have the same problem and I can not figure out what to do

**Comment by maks115015** [comment]
Has anybody solved this problem?

**Comment by kookiekrak** [comment]
@maks115015 are you starting both nodes in the same folder? They need to be in different folders.

email me at tian@tron.network and i can give you a developer slack invite where people can help you out

**Comment by Skyhark-Projects** [comment]
Hi,
I have exactly the same problem. You can reproduce this issue by creating a simple docker like this:

`FROM tronprotocol/tron-gradle

RUN wget https://raw.githubusercontent.com/tronprotocol/TronDeployment/master/deploy_tron.sh -O deploy_tron.sh
RUN bash deploy_tron.sh --app FullNode --net mainnet
# You need to configure different gRPC ports on the same host because gRPC port is available on SolidityNode and FullNodeConfigure and it cannot be set as default value 50051. In this case the default value of rpc port is set as 50041. 
RUN bash deploy_tron.sh --app SolidityNode --net mainnet --trust-node 127.0.0.1:50051 --rpc-port 50041

WORKDIR /FullNode

COPY start.sh /var/start.sh
CMD [ "/var/start.sh" ]`

Start.sh:
`java -jar /FullNode/FullNode.jar -c /FullNode/main_net_config.conf &
java -jar /SolidityNode/SolidityNode.jar -c /SolidityNode/main_net_config.conf &
tail -f /SolidityNode/logs/tron.log`

**Comment by kookiekrak** [comment]
@Skyhark-Projects 
that start.sh file is wrong, it's running both nodes from the same directory.

you need to 

cd /Fullnode & java -jar FullNode.jar & cd ../SolidityNode & java -jar SolidityNode.jar

**Comment by lambda2003** [comment]
I have the same error.  any advice?

ERROR [main] [general](DefaultConfig.java:30) Uncaught exception
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.tron.core.db2.core.SnapshotManager] is defined
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:372)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:332)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1057)
        at org.tron.program.SolidityNode.main(SolidityNode.java:180)

**Comment by nodepaladin** [comment]
I switch to the Mainnet and .... success, so I suggest to use the Mainnet rather than testnet
