### ISSUE TITLE
Fallback function does not work at least on Shasta Testnet

### ISSUE THREAD

**Issue by yukairex** [tronprotocol/java-tron#1677]
The fallback function does not work on the Shasta testnet. It receives TRX pay, but does not trigger function. 

Environment：
    host: "https://api.trongrid.io",
      port: 8090,
      fullNode: "https://api.shasta.trongrid.io",
      solidityNode: "https://api.shasta.trongrid.io",
      eventServer: "https://api.shasta.trongrid.io",
      network_id: "*" // Match any network id

I made a minimized contract to test as following:

pragma solidity ^0.4.23;

contract Test {

    bool test = true;

    function() public payable{
        test = false;
    }

    function getResult() public view returns (bool){
        return test;
    }

}

I sent TRX to contract. The contract balance is non-zero then, but the variable does not change

Thanks

**Comment by zhaohong** [comment]
@yukairex  hi, the fallback function  can't be triggered only be send trx.  the fallback function is called when there is  no-matched function.

**Comment by yukairex** [comment]
@zhaohong Thanks for your reply. The fallback function shall be triggered whenever no-matched function is found OR a contract received TRX (or ETH in ethereum case)

Please see https://solidity.readthedocs.io/en/latest/contracts.html?highlight=fallback for clarification

It is a widely used method in ethereum

**Comment by zhaohong** [comment]
ok thanks @yukairex

**Comment by taihaofu** [comment]
@yukairex, Hi yukairex, Thank you for your question. This is a different need to be attended when you directly transfer your trx to a smart contract account. General speaking, we have two types of contracts in Tron, system contract and smart contract. The way we use to directly transfer trx is called TransferContract which is a system contract. It will not use the logic in smart contract. And this is what exchanges, some Dapps, wallets, tronscan.. use to transfer trx. The benefit is it doesn't need any energy. However, If you want to transfer trx via smart contract and call fallback as what you did in etheruem. You need to use TriggerSmartContract and its related api with no-function name as its argument.  We will consider to improve it as much as what you do in etheruem. But we prefer to keep both of the way for now.

**Comment by yukairex** [comment]
@taihaofu thanks for clarification.

I was also trying sending the trx between two contracts. The idea is that once contract B receives payments from contract A, the fallback method triggers. However, I found it does not work in this way in TRON.

For example, in one contract, the method is 
`function trigger(address _address) public {
          address.transfer(address(this).balance);
}`

In this case, I found _address cannot be a contract address. 

am I correct?

**Comment by taihaofu** [comment]
@yukairex we fully support the contract call contract case(which is normally called internal transaction). 

I guess the problem is the logic you implemented in your fallback function. For transfer() native function, we have a 2300 energy limit for security reason. This means when doing a transfer() you can only have 2300 energy sent into the function in contract A and its related fallback function in contract B. As a result, you can only execute some very easy code in your fallback rather than changing the a property value, such as logging. This is compatible with etheruem.  The 2300 limitation can help your transfer function avoid fallback hacking.

Other function implemented by yourself will have no energy limit (actually you can send all the energy you left through the whole process) unless you expected to do so using gas():
```
bAddress.call.gas(2300)(keccak256("your_function_signature"),<arg1>,.....); 
```
Please tell me if its not the case above.
Thanks.

**Comment by taihaofu** [comment]
@yukairex , Can you provide your related contract code pieces to us if it is still not working? Especially, the fallback part if you implemented in your contract B.

Thanks.

**Comment by taihaofu** [comment]
@yukairex, I see. That make sense to me.
Please check here:
```
function() public payable{
    test = false;
}
```
Just like I mentioned in previous comments, this will cost more than 2300 energy you can have in transfer function. your code would like to fail due to the lacking of energy. 
So what you can do instead is to use an event (log) to track what you did in the whole transfer transaction.
You would probably get the same result when you run this code on ethereum.

Thanks.

**Comment by yukairex** [comment]
@taihaofu 
hmm. Thanks for your clarification
