### ISSUE TITLE
Optimize transaction's duplicate check logic

### ISSUE THREAD

**Issue by olenheim** [tronprotocol/java-tron#1860]
This issue improves transaction duplicate check logic, Before 3.2.2  version when nodes check if one transaction is a duplicate transaction / double spending transaction we will check the whole transaction LevelDB store's transaction hash ID. This way's time complexity is O(n). By now our 
total transaction count is over 100 million，it spends much time. We must find a way to shorten time complexity to O(1).

**Comment by Yrp** [comment]
In order to improve the deduplication performance of the transaction, it is necessary to cache the transaction into the memory, and only judge whether the transaction exists in the cache, and no longer query the transaction in the database. According to the current growth trend, there will be billions of transactions in the future. So it is unrealistic to cache the full amount of transactions in memory, and we need to find a subset of the transaction cached into memory. If a transaction is not queried in the cache, then the transaction must not exist in the database.
# How to find a subset of transactions?
Two fields need to be added when a transaction is created
1. Specify a block to anchor. If the block is on a forked chain, the node on the main chain will not execute the transaction. This block selection interval is (head block number - 65536, head block number), which covers the number of blocks for 3 days.
2. Specify the expiration time, the interval is [current head block time, current head block time +1 day]

Combining the two rules, the trading range we cache in memory is the transaction in these blocks (head block number - 65536, head block number).
# Implement the following features
1. Cache the transaction subset when the program starts
2. When the transactions in a new block are added, delete some existing transactions and maintain a certain amount of space occupied by the cache to reduce the memory usage of the cache.
3. Support for rollback
# How do I delete a transaction that no longer needs to be cached?
Implement a special cache that supports LRU. The key is the transaction id, and the value is the block number where the transaction is located. When there is a transaction in a block to be placed in the cache, the traders in the oldest block are popped up, and the new transaction is stored in the cache.
# How to roll back?
Based on DB2, only solidified transactions are stored in the cache. Unsolidified transactions are still stored in SnapshotImpl.

**Comment by Yrp** [comment]
this is my solution. #1891, I will update it continually

**Comment by Yrp** [comment]
# Test case
1. Preload the transaction to the cache when the program starts. Is there a missing transaction in some blocks?
2. Transactions in the cache need to be deleted from low to high in strict block order, ie transactions in the lowest block height need to be deleted at all times
3. Transactions that are not queried in the cache must not be queried in the database
4. The transactions queried in the cache must be found in the database
5. Block processing performance increased by 8%
6. Transactions in the cache need to always cover the latest 65,536 blocks
