### ISSUE TITLE
NOT_ENOUGH_EFFECTIVE_CONNECTION Problem

### ISSUE THREAD

**Issue by zottirik** [tronprotocol/java-tron#1927]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I am trying to sent TRX.

2. What did you expect to see?
Payment Raw Data.

3. What did you see instead?
NOT_ENOUGH_EFFECTIVE_CONNECTION

**Comment by YG-FLUSH** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> 1. What did you do?
>    I am trying to sent TRX.
> 2. What did you expect to see?
>    Payment Raw Data.
> 3. What did you see instead?
>    NOT_ENOUGH_EFFECTIVE_CONNECTION

I am suffering this problem too.

**Comment by zottirik** [comment]
Is there anybody who knows this issue?

**Comment by varshakhandre14** [comment]
I am getting this error when trying to deploy a smart contract on the private network.

**Comment by jiangyy0824** [comment]
@zottirik This is by design. "minEffectiveConnection" means that you should have more than 1 active peer in your private network. Please set "minEffectiveConnection" to 0 in your config. It should solve your issue. Thanks!

rpc {
port = 50051
#solidityPort = 50061
# Number of gRPC thread, default availableProcessors / 2
# thread = 16

# The maximum number of concurrent calls permitted for each incoming connection
# maxConcurrentCallsPerConnection =

# The HTTP/2 flow control window, default 1MB
# flowControlWindow =

# Connection being idle for longer than which will be gracefully terminated
maxConnectionIdleInMillis = 60000

# Connection lasting longer than which will be gracefully terminated
# maxConnectionAgeInMillis =

# The maximum message size allowed to be received on the server, default 4MB
# maxMessageSize =

# The maximum size of header list allowed to be received, default 8192
# maxHeaderListSize =

# Transactions can only be broadcast if the number of effective connections is reached.
minEffectiveConnection = 1
}
