### ISSUE TITLE
How do you want to develop Smart Contracts?

### ISSUE THREAD

**Issue by sr1993** [tronprotocol/java-tron#2]

**Comment by Yangdaidai** [comment]
Thank you for paying attention to us
In order to keep with the advantages of certainty, termination, and lightweight of virtual machines and the language flexibility of container programming,  TRON is poised to develop the TRON Virtual Machine as an execution environment for its smart contracts in the future. In the future TRON smart contract developers can use almost any high-level language they are good at for TRON smart contract development.
