### ISSUE TITLE
Tron event subscribe doesn't show all events.

### ISSUE THREAD

**Issue by ProtonGustave** [tronprotocol/java-tron#2030]
When i query tronix it doesn't show all occured events, only emited from origin address.
Example tx: `dce2c34aaa4e29192664077343ab080d29cb22652e232f3c6039aac7efed04bf`
There should be 2 events: from origin contract `TXYPSZP4fSQ2YKzQkdW6YsYnCD5u25jGNM`, then that contract call function in another contract `TXBfEmDocfWJSfNaqVBCDdfpctrx6epXXv` and it emit event too. I can only see event from origin address. My curl query:
`curl "https://api.tronex.io/events/transaction/dce2c34aaa4e29192664077343ab080d29cb22652e232f3c6039aac7efed04bf"`

**Comment by jeancky** [comment]
After fully check the transaction info of tx "dce2c34aaa4e29192664077343ab080d29cb22652e232f3c6039aac7efed04bf". We found that it was before MainNet version 3.5 deployed.

The 3.5 version has supported event parser for contract calls contract. And the previous version did not.

You may check this kind of events again now (but not the same transaction, since it won't change).

**Comment by ProtonGustave** [comment]
@jeancky when was approximately 3.5 version deployed?

**Comment by jeancky** [comment]
It has been deployed. About one day after your transaction take place.
