### ISSUE TITLE
test.tronscan.org is not working (prev issue was closed)

### ISSUE THREAD

**Issue by APshenkin** [tronprotocol/java-tron#2086]
Prev closed issue https://github.com/tronprotocol/java-tron/issues/2078

Please answer these questions before submitting your issue. Thanks!

What did you do?
If possible, provide a recipe for reproducing the error.
visit test.tronscan.org

What did you expect to see?
See testnet explorer, as described in docs https://github.com/tronprotocol/Documentation/blob/master/TRX/Tron-exchange.md

What did you see instead?
This site can’t be reached test.tronscan.org took too long to respond.

@jiangyy0823 said to use https://tronscan.org/#/ instead. The test url is unavailable.

But I want to setup testnet node as described in documentation here, not a mainnet node https://github.com/tronprotocol/Documentation/blob/master/TRX/Tron-exchange.md

To test transaction creating etc.

There is shasta testnet, but I can't connect my node to it (see this issue https://github.com/tronprotocol/java-tron/issues/1694)

So I ask you don't close this issue until we can get the answer: How we can setup test node and use explorer and faucet to test integrations with TRON.

Thank you in advance

**Comment by jiangyy0824** [comment]
@APshenkin Shasta testnet doesn't support private connection. test.tronscan.org is also not maintained now. 

If you want to query block data, you can use wallet-cli.

 Thanks.

**Comment by jiangyy0824** [comment]
@APshenkin To query block data on testnet, you can use wallet-cli: https://github.com/tronprotocol/wallet-cli. 

Since this is java-tron project, for shasta-related issues, please seek advice from related team.

**Comment by APshenkin** [comment]
@jiangyy0824 
Yes, I can query block data by wallet-cli, but what about faucets?

```Since this is java-tron project, for shasta-related issues, please seek advice from related team.```
Hm, there is already issue about shasta here, and some contributors comment it. But I will ask also shasta team (they have only discord channel :( )

**Comment by jiangyy0824** [comment]
> @jiangyy0824
> Yes, I can query block data by wallet-cli, but what about faucets?
> 
> `Since this is java-tron project, for shasta-related issues, please seek advice from related team.`
> Hm, there is already issue about shasta here, and some contributors comment it. But I will ask also shasta team (they have only discord channel :( )

You can use eventplugin to store any data you need, and use eventquery to get the block data continuous.  The deploy document is here:
https://github.com/tronprotocol/Documentation/blob/master/English_Documentation/TRON_Event_Subscribe/Tron-eventsubscribe.md

For mainnet event subscribe, we provided query of block, transaction, contract event, please refer to "https://api.tronex.io/transactions". Hope it will help you.

**Comment by APshenkin** [comment]
@jiangyy0824 It's a bad answer

There is still no test enviroment, where we can get everything for integration.

1. Undocumented testnet (notions only in readme)
- no explorer (ok, I can run it by myself)
- no faucet (how I can take test coins for it?)
- yes all API (includes `/walletextension`)
- yes to have your own node

2. Shasta testnet
- yes explorer, but it's not in sync already 3 days https://shasta.tronscan.org/#/
- yes faucet
- not all API are supported (e.g. `/walletextension`)
- unable to setup own node (to e.g. support `walletextension`)

So question is still open

How I can test integration with TRON not on mainnet. It's very important to test all cases, but I can't because of this situation.

And all your answers are not helpful.

**Comment by jiangyy0824** [comment]
@APshenkin For testnet, please use https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf.

For shasta testnet, please ask help from shasta team.

**Comment by gituser** [comment]
I agree with @APshenkin on the points he raised.

There is currently no proper testnet infrastracture for exchanges and related services to integrate TRX adoption.

For the configuration you always mention https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf

* no working faucet (developers need to ask you every time to send coins) - not convenient at all
* no working testnet explorer - also not convenient how to check if transaction has been successful or not?

Also it gives a lot of confusion for beginners the fact that Shasta testnet is different to your own version of testnet.

The easiest solution to this problem is:
* manage Shasta testnet properly 
* give the ability for developers to run a FullNode which will be able to connect to Shasta
* maintain shasta.tronscan.org explorer in sync
* there is already faucet out there for shasta here as well - https://www.trongrid.io/shasta/
* currently you can't use Shasta as there is no endpoint (p2p) to connect to any of the seednodes.

And you always refer to 'shasta team', but on their website the link to discogs is broken and doesn't work here - https://www.trongrid.io/shasta/ https://discord.gg/GsRgsTD.

If you don't want to maintain Shasta testnet, you need to offer more for developers (at least):
* working faucet
* testnet blockchain explorer

All major blockchains have all these tools built in most cases for faster adoption of the cryptocurrency.

Thank you.

**Comment by youngqqcn** [comment]
> I agree with @APshenkin on the points he raised.
> 
> There is currently no proper testnet infrastracture for exchanges and related services to integrate TRX adoption.
> 
> For the configuration you always mention https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf
> 
> * no working faucet (developers need to ask you every time to send coins) - not convenient at all
> * no working testnet explorer - also not convenient how to check if transaction has been successful or not?
> 
> Also it gives a lot of confusion for beginners the fact that Shasta testnet is different to your own version of testnet.
> 
> The easiest solution to this problem is:
> 
> * manage Shasta testnet properly
> * give the ability for developers to run a FullNode which will be able to connect to Shasta
> * maintain shasta.tronscan.org explorer in sync
> * there is already faucet out there for shasta here as well - https://www.trongrid.io/shasta/
> * currently you can't use Shasta as there is no endpoint (p2p) to connect to any of the seednodes.
> 
> And you always refer to 'shasta team', but on their website the link to discogs is broken and doesn't work here - https://www.trongrid.io/shasta/ https://discord.gg/GsRgsTD.
> 
> If you don't want to maintain Shasta testnet, you need to offer more for developers (at least):
> 
> * working faucet
> * testnet blockchain explorer
> 
> All major blockchains have all these tools built in most cases for faster adoption of the cryptocurrency.
> 
> Thank you.

I agree with you!    @gituser 


What's the "shasta team"??   @jiangyy0824
