### ISSUE TITLE
Prevent accept TRX on contract, noname func does not work correctly.

### ISSUE THREAD

**Issue by gfijrb** [tronprotocol/java-tron#2244]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I wrote contract like 

```
uint inc = 0;

function() public payable {
    require(msg.value >= 1000); // prevent reentrancy 
    inc+=1; // counter
}
```

2. What did you expect to see?

I expect that inc will be the 1 after direct send to the contract 

3. What did you see instead?

But TRX was accepted but inc still 0. So that is mean that this does not work correctly. Conclusion is not possible prevent accept TRX in the contract, when you send it directly. 

This is a big BUG!!!

**Comment by jeancky** [comment]
@gfijrb,  This is not a bug.
There are three methods to send TRX into ur contract without trigger the fallback function.

1. Other contract's suicide instruction. **(same in Ethereum)**
2. Send some balance before deploy the contract **(same in Ethereum)**
3. Simple-transfer in TRON (Because simple-transfers only consume bandwidth, no energy is consumed, so, **it cannot trigger fallback() function**)

We are discussing in tip37(https://github.com/tronprotocol/TIPs/issues/37), whether we should forbid using TransferContract & TransferAssetContract for contract address. **Welcome to join the discussion**


However, your code is still incorrect, because the other two methods will still break this limit.

You can read more about this content through this link.
https://mp.weixin.qq.com/s/t3kZqvJVyfjMTo0cymzhWQ

**Comment by gfijrb** [comment]
Thanks for article on chinese))
