### ISSUE TITLE
TransferAssetContract is ambiguous about token

### ISSUE THREAD

**Issue by astudnev** [tronprotocol/java-tron#2423]
API uses asset_name ( not ID ) for TransferAssetContract.

As some token have ambiguous records, for example "SEED", "TWX", "STAR", "BitTorrent", "MajikMunchi", "AI", "TronSilver", "KsumNole", "Mew", "Ruby", "POPPY", "ANTE", "Colorpop", "TronRefunds", "AtomicExchange", "SOON"

and by the name it is not possible to get the actual asset being transfered.

As example, 
There is no way to get asset transfered in transaction 7d7b148ff956ba250dcba569fab60aa914009f082e6fda2d4193c35f80b17365 using the API

**Comment by Sh11thead** [comment]
This transaction is sent in 2018/11/28 11:18:57 before this proposal [https://tronscan.org/#/proposal/14](url) was  approved.
After  proposal# 14 approved,the assetId is reqired for asset transfer,the field assetName should be assigned using assetId

**Comment by ColonelJ** [comment]
You might find the following code useful I wrote to deal with this problem:

https://github.com/ColonelJ/tron-transfers-downloader/blob/b2de629e5e8a1f40c083ce32c8c8e9b606ffa101/index.js#L12-L45

Essentially you check if the asset name consists of all digits, and if not, you lookup the list of assets using the name ordered by ID ascending until you find the first case-sensitive exact match for the name.  That will give you the ID, name and abbreviation.  It's not ambiguous because (case sensitive) asset names were unique before that proposal was approved.

**Comment by astudnev** [comment]
Thank you, i did it other way - check the block number before or after transition, it looks more reliable. With the list lookup - yes, i use the same
