### ISSUE TITLE
Is there any API to get the fees of all transactions in a block?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3146]
### 1. What did you do?

Is there any API to get the fees of all transactions in a block?
In this way, I only need to call once for each block, and I do n’t need to call GetTransactionInfoById once for each transaction.

### 2. What did you expect to see?
i did not find this api.

### 3. What did you see instead?
i need a api to get the fees of all transactions in a block.

**Comment by Alexliu007** [comment]
you can use this API.
/walletsolidity/gettransactioninfobyblocknum(Since Odyssey-v3.7)
Description: Query the list of transaction information in a specific block
$ curl -X POST http://127.0.0.1:8091/walletsolidity/gettransactioninfobyblocknum -d '{"num": 100}'
Parameter num: Block height
Return: The list of transaction information
