### ISSUE TITLE
why the energy of the contract owner is consumed when calling the contract?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3168]
### 1. What did you do?

The problem of contract energy consumption, why the energy of the contract owner is consumed when calling the contract?

**Comment by Alexliu007** [comment]
consume_user_resource_percent : user energy payment percentage of whole energy payment includes contract deployer’s and user's energy payment.
You can query this parameter by "/wallet/getcontract" and can update this parameter by "wallet/updatesetting"

**Comment by BuyOwnEx** [comment]
Please, can you explain this transaction

**Comment by Channing0501** [comment]
> Please, can you explain this transaction
> 
> https://tronscan.org/#/transaction/d57d10a4ac035b303add5d65b3ebb169c75e1641bd1d9d82c73bbfebf99a67b2
> 
> Why "Consume contract owner's Energy" is 4,059 ?
> 
> I expected that caller of contract have to pay all energy 14,631

For USDT, contract owner will undertake 70 percent of energy consumption, you can review it on tronscan: https://tronscan.org/#/contract/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t . But if the contract owner's energy is not enough for consumption, the rest of the energy consumption will be undertaken by caller completely. 
For your transaction, the contract owner did not have the 70 percent of the energy to consume, so the caller need to pay for the rest energy fee.

**Comment by yanghang8612** [comment]
Thanks for the discussion, as he said @Channing0501. 
We defined this feature to facilitate developers to provide a portion of free energy for users to use when calling the contract, in order to attract more users to use the contracts deployed by developers.
One of the more interesting phenomena is that for the first USDT transaction of each block, the user always gets about 4000 free energy from the owner. Here are some examples.
https://tronscan.org/#/transaction/f269c1cd351e710b484b2bc9cb09074a554e4e6fac3bcd6164cb292a292134eb
https://tronscan.org/#/transaction/4398d8e244f7f07e2575d17ae47eadf27520422a0e18a12817a2deeb2407eb7d
https://tronscan.org/#/transaction/a48391455da2a3b8c890138d7244764463a009061f5542d3f385e287aeda2279

**Comment by BuyOwnEx** [comment]
Yes, in my case it was the case "the first USDT transaction of each block". @yanghang8612, thanks a lot
