### ISSUE TITLE
How to confirm that a TRC20 transfer transaction is successful?

### ISSUE THREAD

**Issue by xueyafighting** [tronprotocol/java-tron#3243]

**Comment by Alexliu007** [comment]
1. you can find "transactionInfo.receipt.result=success" through the /walletsolidity/gettransactioninfobyid interface (it is not recommended to use "transactionInfo.result" to judge, because for the http interface, successful transactions do not return this field by default), indicating that TRC20 transfer was successful.

2. you can find "transaction.ret.contractRet = success" is found through the /walletsolidity/gettransactionbyid interface, indicating that the TRC20 transfer was successful.
