### ISSUE TITLE
What is the reason for this transaction Revert error? 

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3262]
### 1. What did you do?

What is the reason for this transaction revert error? 
txid:0cf5abac98c7a9ca05e05bd69f76fcc3a450186d5045f4cf2fa5a4b255acd0b2

**Comment by xueyafighting** [comment]
https://api.trongrid.io/wallet/gettransactioninfobyid?value=0cf5abac98c7a9ca05e05bd69f76fcc3a450186d5045f4cf2fa5a4b255acd0b2

The following conditions generate a require-style exception, which throws a revert error, and only consume the already consumed energy, excluding the unconsumed energy.

1. Call throw
2. If you call the require parameter (expression) the final result is false.
3. If you call a function via a message, but the function does not end correctly (for example, the function runs out of Energy, or throws an exception itself). If Energy is not specified when the function is called, all Energy will be passed in and consumed. Only the Energy value is set to see the difference. This function does not include the low-level operations call, send, delegatecall, or callcode. Low-level operations do not throw an exception, but return false to indicate failure.
4. If you create a contract with the new keyword, but the contract is not created correctly (because you can't specify Energy during contract creation, all Energy is passed in and consumed).
5. If your contract receives TRX via a public function without a payable modifier (including constructors, fallback functions, and generic public functions).
6. transfer() fails
7. Call revert()
8. Reach the maximum function stack depth 64.

**Comment by Benson0224** [comment]
close this issue as we already have a clear answer. thanks.
