### ISSUE TITLE
What is the reason for reporting this error “effective connection:0 lt minEffectiveConnection:1.” ？

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3323]
### 1. What did you do?

What is the reason for reporting this error “effective connection:0 lt minEffectiveConnection:1.” ？

Broadcast transaction 865e9f039ba7119fe335f957ed593feb8d59d1ee5305424acb0e2d1cabfbc802 has failed, effective connection:0 lt minEffectiveConnection:1.

**Comment by Alexliu007** [comment]
It is because your machine is not synchronized to the latest block when broadcasting the transaction.
Block synchronization slow or stop synchronization solution
1.Improve machine configuration, recommend 16core 32GRAM 500G hard drive (ssd)
In the result of the following command, the maximum value of both cpu cores and siblings needs to be greater than or equal to 16.

$cat /proc/cpuinfo | grep -e "cpu cores"  -e "siblings" | sort | uniq
cpu cores   : 8
siblings    : 16

2.Increase the time tolerance of verification transactions
Increase the value of the maxTimeRatio configuration item in the node configuration file to 20.0 or higher.

 vm = {
  supportConstant = false
  minTimeRatio = 0.0
  maxTimeRatio = 20.0
  saveInternalTx = false
}

3.Modify java-tron startup parameters to increase parallel garbage collection parameters：XX:+UseConcMarkSweepGC 

$java -XX:+UseConcMarkSweepGC -jar Fullnode.jar -c config.conf ……
