### ISSUE TITLE
How to generate a TRON network address?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3374]
### 1. What did you do?

How to generate a TRON network address?

**Comment by Alexliu007** [comment]
1.Create TRON address via API
(A) wallet/generateaddress
(B) tronWeb.createAccount()
(c) wallet/createaddress
2.Generate private key and address via wallet or tronscan


Note: To generate an address, you need to activate the account before it can be used. The existing old account sends TRX or TRC10 Token to the new address and broadcast it to the network to complete the account activation.
In addition, if the account has enough bandwidth obtained by freezing TRX, then activating the account will only consume bandwidth, otherwise, activating the account will burn 0.1 TRX

**Comment by woaichixigua07** [comment]
thanks

**Comment by studentforcode** [comment]
Is there any way to recover tron private or seed phrase from wallet address?

How to remove , active address from owner wallet ?

I added multisig and I lost access to the active account.
Thanks ..
