### ISSUE TITLE
@Alexliu007 I assume he is asking how to read the actual message in the exception, e.g.

### ISSUE THREAD

**Issue by JN89** [tronprotocol/java-tron#3435]
@Alexliu007 I assume he is asking how to read the actual message in the exception, e.g.

```solidity
uint256 x = 2;
require(x >= 3, "x less than 3");
```
would result in a failed TX, but the message "x less than 3" is nowhere to be found on the tronscan

I'd also like to know how to properly read these, as error messages are quite important for both, the developer and user

_Originally posted by @1337SEnergy in https://github.com/tronprotocol/java-tron/issues/3407#issuecomment-704773755_

**Comment by Alexliu007** [comment]
According to txid, query the contractResult field in the result returned through the wallet/gettrasactioninfobyid interface. If the field is not empty, you can see the abi code value of the message, convert the code value into a string, and find the reason for the error.
For example, txid:e5e013e81cb50a4c495a11c8130ad165a4e98d89b9e3fb5b79e6111bf23b31ed
https://api.trongrid.io/wallet/gettransactioninfobyid?value=e5e013e81cb50a4c495a11c8130ad165a4e98d89b9e3fb5b79e6111bf23b31ed

Return contractResult data:
"contractResult": [
"08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001e536166654d6174683a207375627472616374696f6e206f766572666c6f770000"
]
Converting 1e536166654d6174683a207375627472616374696f6e206f766572666c6f77 into a string is: SafeMath: subtraction overflow, this transaction is because the transfer address overflowed during the subtraction operation during the transfer. The specific failure may be caused by insufficient balance. You need to check the address balance and transfer amount，Other errors can be checked according to the specific reason of the error.
