### ISSUE TITLE
OUT_OF_TIME error

### ISSUE THREAD

**Issue by Cletitia** [tronprotocol/java-tron#3456]
I received an OUT_OF_TIME error during triggering a smart contract. This error does not appears every time. What exactly causes the problem?

**Comment by Alexliu007** [comment]
At present, TRON has a global setting. The execution time of calling smart contract transactions cannot exceed 50ms. This 50ms parameter can be modified by SR voting. If the contract code is very complex and the execution time exceeds 50ms, it will trigger an OUT_OF_TIME error and deduct all fee_limit fees.

If the same contract function sometimes triggers the OUT_OF_TIME error, sometimes it does not trigger the OUT_OF_TIME error, indicating that the complexity of the contract code is at a critical value. Because the machine performance of different SRs is different, it will cause intermittent triggering.

In addition, it should be noted that due to the fluctuation of SR machine performance, there will be a small probability that the contract function call with very low complexity will also trigger the OUT_OF_TIME error. It is recommended that users set the appropriate fee_limit according to the contract complexity to prevent excessive losses caused by excessive setting of fee_limit.
