### ISSUE TITLE
How to solve the situation that the transaction broadcast is successful but not on the chain?

### ISSUE THREAD

**Issue by woaichixigua07** [tronprotocol/java-tron#3464]
### 1. What did you do?

How to solve the situation that the transaction broadcast is successful but not on the chain?

**Comment by Alexliu007** [comment]
It is normal that the transaction broadcast is successful but not on the chain. Other nodes may not continue to broadcast to the SR due to some other unknown reasons, so the transaction cannot be checked. In this case, it is best to add a delay judgment. A transaction that is not on the chain for a certain period of time can be rebroadcast within the validity period of the transaction, or recreate the transaction after the validity period.
