### ISSUE TITLE
what does NOT_ENOUGH_EFFECTIVE_CONNECTION represent for?

### ISSUE THREAD

**Issue by Cletitia** [tronprotocol/java-tron#3465]
### 1. What did you do?
I run a full node myself. I tried to broadcast a transaction but received NOT_ENOUGH_EFFECTIVE_CONNECTION. What’s the reason causes this?

**Comment by Alexliu007** [comment]
It is because your machine is not synchronized to the latest block when broadcasting the transaction.
Block synchronization slow or stop synchronization solution
1.Improve machine configuration, recommend 16core 32GRAM 500G hard drive (ssd)
In the result of the following command, the maximum value of both cpu cores and siblings needs to be greater than or equal to 16.

$cat /proc/cpuinfo | grep -e "cpu cores" -e "siblings" | sort | uniq
cpu cores : 8
siblings : 16

2.Increase the time tolerance of verification transactions
Increase the value of the maxTimeRatio configuration item in the node configuration file to 20.0 or higher.

vm = {
supportConstant = false
minTimeRatio = 0.0
maxTimeRatio = 20.0
saveInternalTx = false
}

3.Modify java-tron startup parameters to increase parallel garbage collection parameters：XX:+UseConcMarkSweepGC

$java -XX:+UseConcMarkSweepGC -jar Fullnode.jar -c config.conf ……
