### ISSUE TITLE
Automatic deduction to network staking wallet after unstaking 

### ISSUE THREAD

**Issue by Anyaoha** [tronprotocol/java-tron#3610]

**Comment by andelf** [comment]
Describe your activities with more details.

- What app/browser/browser-extension/libraries are you using?
- What did you do, with more details. Any button clicked or action performed.
- Any available transaction id?

**Comment by dmf3030** [comment]
This feels like you got hacked.  I looked at that address and it received two chunks of TRX which it then forwarded on.  Both chunks came out of wallets who had unfrozen their TRX and then about 10 blocks later that TRX was sent to the address you posted.  If I had to guess its some exploit thats leaking keys and this person has a script that watches accounts and send out any TRX it finds to an address that then passes the trx along.  They haven't made their script look for frozen assets though, so the only way around this would be to script your own unfreeze and send to a safe address and try to beat their script to the punch and thus send your TRX away before they stole it.  Thats just my hunch but from looking at that address and where its sending TRX this seems like an exploit.  

Definitely list what wallet or extension your using and think about what dapps you may have used or if you ever entered your private key anywhere.

**Comment by Anyaoha** [comment]
Well this is really a big issue in the Tron ecosystem because if such scripts could be deployed to their network to look for accounts that just unfreezes their TRX and gets it hacked, it just says a lot that needs to be done to close the loop holes before someone else gets hurt and hacked.


The two accounts of mine that got hacked were both frozen in the Klever wallet. And as soon as I unstacked them, they both disappeared. And the funny thing is that, at the time the two transactions got back-dated 7 hours... So I suspect whatever scripts they’re using, runs constantly and checks all accounts that are staked. 

I haven’t used those accounts in any dapps. I just buy TRX and stake.... 

But now I don’t trust the TRX ecosystem.

**Comment by dmf3030** [comment]
Hate to say it but this isn't about Tron at all, though I totally understand why you would be frustrated and looking for answers.  Writing a script to watch wallets for an unfreeze happens outside the network and you could do that for any blockchain, the real issue is that somehow your private key got compromised.  Once the hacker had your key then their script to watch wallets was just something they put together because whatever exploit they are using they are getting enough keys that they need to automate the TRX extraction.  

So the real question would be whether there was some way when you setup your Klever wallet, that you could have had your keys compromised.  Were they copied to your clipboard in a way that they could have been see by spyware, or was there anywhere else that you might have placed your keys where they could be seen.  If your not using dapps then its unlikely you entered your keys somewhere by accident so really its gotta be about how you setup your wallet.  Have you spoken to the Klever guys at all to see if there are other users reporting the same thing?

**Comment by Anyaoha** [comment]
I wrote down my key separately. In a journal. Same place I wrote down other keys to different wallets and cryptocurrencies I have, and those are still intact. If someone had seen my journal they would have also stolen other crypto from other wallets where they are way more than my TRX... And just so you know, this happened to the two TRX accounts on Klever which I use.
So I do think TRX needs to be checked out. 


Sent from Yahoo Mail for iPhone


On Wednesday, January 20, 2021, 6:45 PM, dmf3030 <notifications@github.com> wrote:




Hate to say it but this isn't about Tron at all, though I totally understand why you would be frustrated and looking for answers. Writing a script to watch wallets for an unfreeze happens outside the network and you could do that for any blockchain, the real issue is that somehow your private key got compromised. Once the hacker had your key then their script to watch wallets was just something they put together because whatever exploit they are using they are getting enough keys that they need to automate the TRX extraction.

So the real question would be whether there was some way when you setup your Klever wallet, that you could have had your keys compromised. Were they copied to your clipboard in a way that they could have been see by spyware, or was there anywhere else that you might have placed your keys where they could be seen. If your not using dapps then its unlikely you entered your keys somewhere by accident so really its gotta be about how you setup your wallet. Have you spoken to the Klever guys at all to see if there are other users reporting the same thing?

**Comment by Benson0224** [comment]
Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.

**Comment by Anyaoha** [comment]
Yes the issue hasn’t been resolved!!Keep it open!! 


Sent from Yahoo Mail for iPhone


On Wednesday, February 17, 2021, 7:43 PM, Benson <notifications@github.com> wrote:




Close this issue as no feedback for a long time, feel free to reopen it if you still see the issue. thanks.
