### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by hashpaypie** [tronprotocol/java-tron#3673]
1131 tests completed, 51 failed, 29 skipped

> Task :framework:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':framework:test'.
> There were failing tests. See the report at: file:///root/tron/java-tron/framework/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 24m 27s
50 actionable tasks: 50 executed

编译的时候报错。jdk装的是 Oracle JDK 1.8
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

**Comment by kunlunxuejue11** [comment]
Which code branch?
What compile command did you use?

**Comment by hashpaypie** [comment]
branch GreatVoyage-v4.1.2
root@ls-:~/tron/java-tron# git branch
* (HEAD detached at GreatVoyage-v4.1.2)
  develop

command use gradlew build
root@ls-:~/tron/java-tron#  ./gradlew build

Master Branch is  same error

root@ls-:~/tron/java-tron# gradle -version

------------------------------------------------------------
Gradle 5.6.4
------------------------------------------------------------

Build time:   2019-11-01 20:42:00 UTC
Revision:     dd870424f9bd8e195d614dc14bb140f43c22da98

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_281 (Oracle Corporation 25.281-b09)
OS:           Linux 4.15.0-46-generic amd64

At first I thought this was a Gradle version problem. I have retreated from 6.0 above to 5.6.4 and still report errors

**Comment by hashpaypie** [comment]
> Which code branch?
> What compile command did you use?
branch GreatVoyage-v4.1.2
root@ls-:~/tron/java-tron# git branch

(HEAD detached at GreatVoyage-v4.1.2)
develop
command use gradlew build
root@ls-:~/tron/java-tron# ./gradlew build

Master Branch is same error

root@ls-:~/tron/java-tron# gradle -version

Gradle 5.6.4
Build time: 2019-11-01 20:42:00 UTC
Revision: dd870424f9bd8e195d614dc14bb140f43c22da98

Kotlin: 1.3.41
Groovy: 2.5.4
Ant: Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM: 1.8.0_281 (Oracle Corporation 25.281-b09)
OS: Linux 4.15.0-46-generic amd64

At first I thought this was a Gradle version problem. I have retreated from 6.0 above to 5.6.4 and still report errors

**Comment by Benson0224** [comment]
Seems it is a test case failure, could you try bellow command which skipped the test part. 
`./gradlew build -X test`

**Comment by viputopia** [comment]
> Seems it is a test case failure, could you try bellow command which skipped the test part.
> `./gradlew build -X test`

~/tron/java-tron# ./gradlew build -X test
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :build from command line.
> Unknown command-line option '-X'.

* Try:
Run gradlew help --task :build to get task usage details. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s

Skipping tests also failed to compile

**Comment by Benson0224** [comment]
please kindly share the failure log here for further investigation. thanks.

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time, feel free to re-open it if you still see the issue. thanks.

**Comment by urahamat01** [comment]
The plugins `android_wifi_info, esys_flutter_share, flt_telephony_info, fluttertoast, get_ip, imei_plugin` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
Note: /home/zakaria/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/android_wifi_info-0.1.1/android/src/main/java/com/smaho/eng/android_wifi_info/AndroidWifiInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.7/lib/date_range_picker.dart:96:25: Error: The getter 'display1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'display1'.
        headerTextTheme.display1.copyWith(color: dayColor, height: 1.4);
                        ^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.7/lib/date_range_picker.dart:98:25: Error: The getter 'subhead' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subhead'.
        headerTextTheme.subhead.copyWith(color: yearColor, height: 1.4);
                        ^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.7/lib/date_range_picker.dart:455:51: Error: The getter 'body1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.
        TextStyle itemStyle = themeData.textTheme.body1;
                                                  ^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.7/lib/date_range_picker.dart:470:49: Error: The getter 'body2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body2'.
          itemStyle = themeData.accentTextTheme.body2;
                                                ^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.7/lib/date_range_picker.dart:475:49: Error: The getter 'body2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body2'.
          itemStyle = themeData.accentTextTheme.body2;
                                                ^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.7/lib/date_range_picker.dart:483:49: Error: The getter 'body2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body2'.
          itemStyle = themeData.accentTextTheme.body2;
                                                ^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.7/lib/date_range_picker.dart:495:43: Error: The getter 'body1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.
          itemStyle = themeData.textTheme.body1
                                          ^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.7/lib/date_range_picker.dart:502:35: Error: The getter 'body2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body2'.
              themeData.textTheme.body2.copyWith(color: themeData.accentColor);
                                  ^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.7/lib/date_range_picker.dart:564:46: Error: The getter 'subhead' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subhead'.
                  style: themeData.textTheme.subhead,
                                             ^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.7/lib/date_range_picker.dart:946:49: Error: The getter 'body1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'body1'.
    final TextStyle style = themeData.textTheme.body1;
                                                ^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/date_range_picker-1.0.7/lib/date_range_picker.dart:957:35: Error: The getter 'headline' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline'.
            ? themeData.textTheme.headline
                                  ^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/home/zakaria/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/zakaria/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by WAT251922ty** [comment]
Wallet. Addresses. TRX. TJA3ww2otwXSURd27AzXyUqMTuDF8ZfwEN
Recive. Token.
Tyu67th8
***@***.***

Thank. You


ในวันที่ จ. 20 ก.ย. 2021 16:20 MD. RAHAMAT ULLAH ***@***.***>
เขียนว่า:
