### ISSUE TITLE
Need Guidence to integrate TRC20 with our java backend application

### ISSUE THREAD

**Issue by Jorgeadverd** [tronprotocol/java-tron#3678]
Hi All,

We have ERC20 token running with out local node and we also want to integrate the TRC20 token with our backend java code, Can someone please guide us do we need to run the local node for TRC20 as well?

Or we can connect directly to TRON blockchain network and can operate below operations such as 

1- Create wallet address
2- Send  TRC20 token to another address 
3- Receive TRC20 token from another address 

Make operation which required in our platforms to allow buy token and purchase content with token , like that

Can some Please help us for the same because we are not getting right understand how the TRON Java will work.

Many thanks in advance.

**Comment by Benson0224** [comment]
Here is the guide of how to deploy your own fullnode: https://developers.tron.network/docs/fullnode .

Yes, you can also directly connect TRON network, for example using trongrid, here is the trongrid link: https://www.trongrid.io/ 
Please check the answers to your questions below:
1- Create wallet address
Suggest generating all address offline instead of using FullNode API,  please join our Telegram Dev Group if you have more question on Generating address, here is the group link: https://t.me/TronOfficialDevelopersGroupEn
2- Send TRC20 token to another address
Yes, it can be done both via Your own FullNode or via Trongrid. 
3- Receive TRC20 token from another address
Yes, it can be done both via Your own FullNode or Trongrid.

**Comment by Benson0224** [comment]
We will close this issue as no update for a long time. 
Please feel free to re-open this issue if you still see it. thanks.

**Comment by Jorgeadverd** [comment]
Hi @Benson0224 

Thanks for details, we are studying it will get back to you soon.

meanwhile close the case.

**Comment by Benson0224** [comment]
> @Benson0224 i am trying to setup tron in our machine but it is showing error related to gradle can you help me to resolve the issue

I would suggest you create a new issue and list the detailed error message there.

**Comment by jatinkumar999** [comment]
![Screenshot (90)](https://user-images.githubusercontent.com/79906548/114174898-f0231400-9956-11eb-9cbc-faecbe3ebcfc.png)

**Comment by Benson0224** [comment]
> ![Screenshot (90)](https://user-images.githubusercontent.com/79906548/114174898-f0231400-9956-11eb-9cbc-faecbe3ebcfc.png)
> ..@Benson0224 sir i am facing this issue in the setup of tron node in my machine,can you help me to figure it out
check this guide on how to set up a fullnode
https://developers.tron.network/docs/fullnode
