### ISSUE TITLE
Tron transaction is fail from binace

### ISSUE THREAD

**Issue by navneetboghani** [tronprotocol/java-tron#3692]
### 1. What did you do?

FAIL-CPU TIMEOUT FOR 'PUSH1' OPERATION EXECUTING

### 2. What did you expect to see?
https://tronscan.org/#/transaction/2d658223b9ce79fd62919b971147af8edfada3ddd071a503930d010a5af40657

### 3. What did you see instead?
Please help me if you have information

**Comment by Alexliu007** [comment]
USDT transfer timeout problem, the reason may be related to the sr machine. However, even the best machine may time out because the CPU is busy, but the probability of this occurrence is relatively low. You can make the transfer again. For related timeout errors, please refer to the [document](https://developers.tron.network/docs/faq#2-why-would-i-trigger-out_of_time-error-when-calling-contract-function)

**Comment by Benson0224** [comment]
We will close this issue since no update for a long time. 
Please feel free to re-open it if you still see the issue, thanks.
