### ISSUE TITLE
Out of Energy - Atomicwallet 

### ISSUE THREAD

**Issue by juancor2021** [tronprotocol/java-tron#3707]
### 1. What did you do?
FAIL-Out of Energy>

### 2. What did you expect to see?
https://tronscan.org/#/transaction/052ed38fab7937a8328f8ac9de01eb33db9543c8e3cf8abc5fb6d9672c6f4cc3

### 3. What did you see instead?

USDT transfer "FAIL-Out of Energy" I send from Atomicwallet, how to solved?
Help please

**Comment by Alexliu007** [comment]
Hi，When the address was transferred out of USDT, it failed because it did not have enough TRX balance. you can use wallet/getaccountbalance to check. curl -X POST \
  https://api.trongrid.io/wallet/getaccountbalance \
  -H 'Authorization: Bearer test' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: ac50c62d-8a37-4760-8be1-aecbbad56b9d' \
  -H 'TRON_PRO_API_KEY: 25f66928-0b70-48cd-9ac6-da6f8247c663' \
  -H 'cache-control: no-cache' \
  -d '{
    "account_identifier": {
        "address": "TXC26Mb4g5LUfD2HBn8eYdMJuwb5oAJDfq"
    }, 
    "block_identifier": {
        "hash": "0000000001b2bda118730f575ce75ebce2f7f8b1caa41603ed8539feb821ffc0",
        "number": 28491169
    },
    "visible": true
}'

**Comment by juancor2021** [comment]
> 
> 
> Hi，When the address was transferred out of USDT, it failed because it did not have enough TRX balance. you can use wallet/getaccountbalance to check.
> 
> curl -X POST
> https://api.trongrid.io/wallet/getaccountbalance
> -H 'Content-Type: application/json'
> -H 'Postman-Token: ac50c62d-8a37-4760-8be1-aecbbad56b9d'
> -H 'TRON_PRO_API_KEY: 25f66928-0b70-48cd-9ac6-da6f8247c663'
> -d '{
> "account_identifier": {
> "address": "TXC26Mb4g5LUfD2HBn8eYdMJuwb5oAJDfq"
> },
> "block_identifier": {
> "hash": "0000000001b2bda118730f575ce75ebce2f7f8b1caa41603ed8539feb821ffc0",
> "number": 28491169
> },
> "visible": true
> }'
> 
> **return:**
> {
> **"balance": 0,**
> "block_identifier": {
> "hash": "0000000001b2bda118730f575ce75ebce2f7f8b1caa41603ed8539feb821ffc0",
> "number": 28491169
> }
> }

how i can settin up  a higger fee, i must edit some file, please indicateme thaht thanks in advice.

**Comment by Benson0224** [comment]
We will close this issue as @Alexliu007  already give the correct answer, please feel free to re-open the issue if you still run into it.  thanks.
