### ISSUE TITLE
I suggest you use telnet to test whether the nodes are available, as they may have blocked ping requests.

### ISSUE THREAD

**Issue by bungfut** [tronprotocol/java-tron#3783]
I suggest you use telnet to test whether the nodes are available, as they may have blocked ping requests.

_Originally posted by @Starsakary in https://github.com/tronprotocol/java-tron/issues/3780#issuecomment-840368963_

**Comment by Benson0224** [comment]
I don't see the necessity of doing this.

Since the node is already enabled HTTP port and RPC port, it is enough to query the status of the nodes. 
for example, the first node in the public node list is 3.225.171.164, it is very easy to query the node status via the below URL:

- http://3.225.171.164:8090/wallet/getnodeinfo
- http://3.225.171.164:8090/wallet/getnowblock

**Comment by bungfut** [comment]
Duplicate of #
