### ISSUE TITLE
FAIL-TIMEOUT FOR CONTRACT EXECUTION - 99TRX Burnt

### ISSUE THREAD

**Issue by jenishngl** [tronprotocol/java-tron#3854]
### 1. What did you do?
I was trying to borrow TUSD from JustLend and that transaction errored out. Below is the transaction. The issue is it burnt 99.99TRX as well. I dont think i will be able to get back the burnt TRX. But checking if there is any issue

https://tronscan.org/#/transaction/f842fe651715668eb7d4bd2225a71e951f5ee138021e6a6eabfc5cd96ca017dd

### 2. What did you expect to see?
Borrow option in JustLend to work successfully. Also even if the transaction errors out, why burn the TRX as a waste of resourse

### 3. What did you see instead?
Failed transaction with TRX lost

**Comment by Starsakary** [comment]
The energy specified by Feelimit will be completely consumed once the contract execution times out.

See [resource model](https://developers.tron.network/docs/resource-model).

**Comment by jenishngl** [comment]
Yes, but don't you think its waste of resource even for a failed transaction

--Jenish

**Comment by Starsakary** [comment]
Regardless of whether the transaction is successful or not, its execution process also occupies network resources. If a failed transaction costs nothing, the network will be easy to attack till collapse.

Please always remember that blockchains are decentralised systems. The cost you pay is in order to maintain the security of the network.

**Comment by jenishngl** [comment]
Thank you for the clarification.

--Jenish

**Comment by Starsakary** [comment]
I'm closing this issue then. Feel free to reopen this or open a new issue for questions.

**Comment by lazike66** [comment]
Great
