### ISSUE TITLE
updateBrokerageRatio Issue

### ISSUE THREAD

**Issue by osiz-blockchainapp** [tronprotocol/java-tron#3855]
Hi,
Running private network, cannot update brokerage ratio

### 1. What did you do?
I updated committee paramter in conf file as 
committee = {
  allowCreationOfContracts = 1  //mainnet:0 (reset by committee),test:1
  allowMultiSign = 1 //mainnet:0 (reset by committee),test:1
  allowChangeDelegation = 1
  allowDelegateResource = 1
  allowSameTokenName = 1
  allowTvmTransferTrc10 = 1
  allowTvmConstantinople = 1
  allowTvmSolidity059 = 1
  allowMarketTransaction = 1
}
In **CLI**, UpdateBrokerage "address" 25
But it wont update in chain parameters:
{
   "key": "getChangeDelegation"
}
 
### 2. What did you expect to see?
Brokerage ratio updated successfully.

### 3. What did you see instead?
contract validate error : contract type error, unexpected type [UpdateBrokerageContract]

**Comment by Alexliu007** [comment]
Hi, building a TRON private chain, pls refer to this [document](https://developers.tron.network/docs/tron-private-chain).
In order to be consistent with the mainnet environment, it is necessary to keep the proposal in the private chain the same with the mainnet proposal. 
Please note: some proposals have a sequential order, and it is recommended to make a proposal according to the proposal_id of the main network.
thanks!

**Comment by osiz-blockchainapp** [comment]
> Hi, building a TRON private chain, pls refer to this [document](https://developers.tron.network/docs/tron-private-chain).
> In order to be consistent with the mainnet environment, it is necessary to keep the proposal in the private chain the same with the mainnet proposal.
> Please note: some proposals have a sequential order, and it is recommended to make a proposal according to the proposal_id of the main network.
> thanks!

Hi,
Proposals are in sequential order.But i have to update brokerage ratio.still having same error "contract validate error : contract type error, unexpected type [UpdateBrokerageContract]"

**Comment by Alexliu007** [comment]
> > Hi, building a TRON private chain, pls refer to this [document](https://developers.tron.network/docs/tron-private-chain).
> > In order to be consistent with the mainnet environment, it is necessary to keep the proposal in the private chain the same with the mainnet proposal.
> > Please note: some proposals have a sequential order, and it is recommended to make a proposal according to the proposal_id of the main network.
> > thanks!
> 
> Hi,
> Proposals are in sequential order.But i have to update brokerage ratio.still having same error "contract validate error : contract type error, unexpected type [UpdateBrokerageContract]"

hi,  Please provide the following information：
1.Please use the interface wallet/getnodeinfo to provide the node version
2. What are the specific parameters of the request?
3. Please use the interface wallet/listproposals to provide a list of private chain proposals

Or you can add Tron developer group so that we can communicate in time to solve your problem.

Telegram TRON English Developer Technical Support：
https://t.me/TronOfficialDevelopersGroupEn

Thanks!
