### ISSUE TITLE
How to get TRC20&721 by blockNum?

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [tronprotocol/java-tron#3861]

**Comment by Alexliu007** [comment]
Hi, you need to parse the transaction and get the contract address from the transaction. 
I see that you have a lot of questions here. You can join the TRON developer group so that your questions will be answered in time.

Telegram TRON English Developer Technical Support：
https://t.me/TronOfficialDevelopersGroupEn
Wechat group:
hello-zyuming

**Comment by oushu1zhangxiangxuan1** [comment]
> Hi, you need to parse the transaction and get the contract address from the transaction.
> I see that you have a lot of questions here. You can join the TRON developer group so that your questions will be answered in time.
> 
> Telegram TRON English Developer Technical Support：
> https://t.me/TronOfficialDevelopersGroupEn
> Wechat group:
> hello-zyuming

Thanks！I got no Telegram now and I add hello-zyuming's Wechat, but haven't received approval.
By the way, my EN is poor, cloud we communicate in CH?
😂

**Comment by Benson0224** [comment]
Thanks for your contribution to https://github.com/tronprotocol/java-tron
This issue will be closed since no update for a long time. Please let us know if you still not in our WeChat group. 
Please feel free to re-open this issue if you still see it, thanks.
