### ISSUE TITLE
How long does the private chain need to be synchronized？

### ISSUE THREAD

**Issue by johnzhou123** [tronprotocol/java-tron#4148]
How long does the private chain need to be synchronized？

I built it with reference to this URL
https://cn.developers.tron.network/docs/%E7%A7%81%E9%93%BE%E6%90%AD%E5%BB%BA

one supernode ,one fullnode
I think it's very slow. It took more than two days to synchronize to tens of thousands of blocks

**Comment by vivian-kang** [comment]
For private chain, it is not running too long time, so the number of blocks is limited. it will not take too much time to complete the synchronization. 

Because of only one supernode, so the latest block generated by the supernode is the recent block of the private chain, and you can check logs of fullnode and supernode to see the block number current processed.

If there still exists sync issue, please refer to this doc to solve it: https://developers.tron.network/docs/faq#8-how-to-solve-the-problem-of-slow-node-block-synchronization-or-stop-synchronization

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time. 
Please feel free to re-open it if you still see the issue, thanks
