### ISSUE TITLE
not receiving activation email from tronscan

### ISSUE THREAD

**Issue by bhavyasarin** [tronprotocol/java-tron#4185]
### 1. What did you do?

i registered to tronscan and then it says you will receive email to activate but i didnt got any

**Comment by Benson0224** [comment]
Please use connect wallet instead of login, thanks

Make sure you have installed the tronlink chrome extensions.  thanks. https://chrome.google.com/webstore/detail/tronlink%EF%BC%88%E6%B3%A2%E5%AE%9D%E9%92%B1%E5%8C%85%EF%BC%89/ibnejdfjmmkpcnlpebklmnkoeoihofec 

![image](https://user-images.githubusercontent.com/61768920/146109799-ff5b1898-651c-42e0-bc9c-c3e92cd70188.png)

**Comment by Benson0224** [comment]
Thanks for your contribution to java-tron.
This issue will be closed as no update for a long time.
Please feel free to re-open it if you still see the issue, thanks
