### ISSUE TITLE
Tron website wallet ONLINE ??!

### ISSUE THREAD

**Issue by Kowai** [tronprotocol/java-tron#433]
How come that any user logging on the tron.network website can see the wallet under developpement ?!! Don't you think some might send TRX there ? Don't you think you guys should put some 2th step verification there ?
Don't you think there should be a developpement website OFFLINE and try the improvement THERE and only when you release something you can put it on the official online one ??

When i asked Admin on telegram group they just answered me "look there is no announcement about the wallet so it means this is not working yet.. What ?! Why does the platform on Tron network give me an adress i can send coins in then ?? Where do they go ? lost ?!

I really feel great concern about your project and how (un)professional it is seems to be..

**Comment by Rovak** [comment]
Hi Kowai, i believe by placing the block explorer / wallet on the official website that there will be more people who are testing the network, finding bugs and making the main net more stable as a result.

There are some pretty clear warnings when creating an account and on the account page that you shouldn't send TRX to the testnet. I did some testing to see what happens if you try to send TRX to a testnet address and it looks like it is pretty hard to do so:

Binance throws a `withdraw address error`

![screenshot from 2018-04-14 10-20-392](https://user-images.githubusercontent.com/376155/38766165-7eaa4030-3fce-11e8-9df9-30b955f48f5e.png)

MEW considers it an invalid address. In this case i tried to send ETH, but i see no reason why the check wouldn't be done when sending TRX

![screenshot from 2018-04-14 10-29-29](https://user-images.githubusercontent.com/376155/38766179-be1d2d86-3fce-11e8-986c-a5291a13c857.png) 

Until main net is released and while TRX is still considered an Ethereum token i think that most wallets will validate the address (which is as simple as checking if the address starts with `0x`) before making a transaction.

When main net is released i agree that it should be made impossible to use testnet addresses on main net and vice versa and that test/development network should only be reachable by developers and testers.

(This is my personal opinion and not an official response)

**Comment by Rovak** [comment]
Closing this as this doesn't seem to be an issue, feel free to reopen if there are any other concerns.
