### ISSUE TITLE
Failed to retrieve the contract coin balance of an address with error "class org.tron.core.vm.program.Program$OutOfTimeException : CPU timeout for 'SWAP1' operation executing"

### ISSUE THREAD

**Issue by arayalways** [tronprotocol/java-tron#4416]
Failed to retrieve the contract coin balance of an address with error 
"class org.tron.core.vm.program.Program$OutOfTimeException : CPU timeout for 'SWAP1' operation executing"

How it happens while I am just get my address's coin balance??

**Comment by yanghang8612** [comment]
There are two reasons for the cpu timeout, one is that the smart contract execution logic is too complex, and the other is because the node machine is experiencing STW(Stop The Wold for JVM) during smart contract execution.
I infer that this timeout you have should be the latter. For a query request, I suggest you just retry.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
