### ISSUE TITLE
Java-tron - Release linux/arm64 builds

### ISSUE THREAD

**Issue by andreclaro** [tronprotocol/java-tron#4692]
## Description
Release `linux/arm64` builds for java-tron.

## Related Issues
- https://github.com/tronprotocol/java-tron/issues/4248
- https://github.com/tronprotocol/java-tron/issues/4525

## Why this feature is important
- Take advantages of running the nodes on top Arm CPU architecture machines, such as, AWS Graviton2/3. The main benefits are costs reduction and performance increase. For further details consult: https://aws.amazon.com/ec2/graviton and https://about.gitlab.com/blog/2021/08/05/achieving-23-cost-savings-and-36-performance-gain-using-gitlab-and-gitlab-runner-on-arm-neoverse-based-aws-graviton2-processor
" Our latest cost analysis and performance benchmarks show that customers can realize cost savings of up to 23% and performance gains of up to 36% by deploying the GitLab application and GitLab Runner on the Arm-based Graviton2 when compared to the x86 based M5/C5 EC2 instances." 

- Enable developers to run `java-tron` on their MacBook Pro M1/M2 laptops.

**Comment by halibobo1205** [comment]
Due [ExchangeProcessor](https://github.com/tronprotocol/java-tron/blob/master/chainbase/src/main/java/org/tron/core/capsule/ExchangeProcessor.java#L19) use `Math.pow`  to calculate instead of `StrictMath.pow`,  `Math.pow` for jdk1.8_x86 being specially implemented.

In java8, the default behavior of Math is using any available FPU like 8087. The results of float operations might be platform-dependent.
In later versions, the default behavior changes and will use IEEE-float(SSE2 instructions). So you can't update JDK/JRE without a proposal-fork.

In detail, java-tron's double arithmetic will use x87 instructions. And is difficult to port to other languages or  platform, since all modern languages use ieee-compatible and stable arithmetic for float numbers.

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Comment by microcai** [comment]
so, tron use java, but can only run on x86_64 ?
