### ISSUE TITLE
USDT REVERT TRC-20

### ISSUE THREAD

**Issue by xcj1212** [tronprotocol/java-tron#5059]
### System information

java-tron version: `java -jar FullNode.jar -v`
OS & Version: Windows/Linux/OSX

### 1. What did you do?

I try to transfer the USDT in the wallet, but it shows REVERT, the USDT balance has not changed, and my USDT and TRX are sufficient.

### 2. What did you expect to see?

Successfully transferred USDT to another address

### 3. What did you see instead?

FAILED-REVERT

**Comment by xcj1212** [comment]
![Uploading 141728D4-05EC-473B-BEF0-AB10C8F0F2C1.png…]()

**Comment by sunflower-sun** [comment]
Revert error occurs when executing smart contract code, and usually because of the require expresssion failure. And Revert when transferring USDT is usually due to the address being blocked, you can check if the address is blocked by invoking "isBlackListed" of USDT. https://tronscan.org/#/token20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/code . If not, you can share the transactionid.

**Comment by xcj1212** [comment]
how to use "isBlackListed" of USDT, I'm not very good at coding, thanks for your reply

**Comment by sunflower-sun** [comment]
https://tronscan.org/#/token20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t/code In this page of tronscan, you can find the "Contract" - "Read Contract", then input your address into the isBlackListed method of USDT.
![image](https://user-images.githubusercontent.com/100661145/227088314-15887878-77de-4855-9661-03119059428c.png)

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
