### ISSUE TITLE
There are so many "timeout" message in tron.log

### ISSUE THREAD

**Issue by KaiQiu9527** [tronprotocol/java-tron#5226]
### System information

OS : Linux
JVM : Oracle Corporation 1.8.0_131 amd64
Git : https://github.com/tronprotocol/java-tron/commit/da2673cd28e368b68c9a8056b7c3aa15ec880bf7
Version : 4.7.1
Code : 17673

### 1. What did you do?

I have four fullnodes using the same machine, which is 16U32G with HDD harddisk.

### 3. What did you see instead?
(1) CPU timeout
Three nodes of them are frequently suffering "VM halted: [CPU timeout for 'XXXX' operation executing]", but the other one seldom meet this situation. Is it related the the machine performance or the block itself? Will it affect the node sync speed?
![image](https://github.com/tronprotocol/java-tron/assets/16130943/1aad7e57-83ad-4941-88a9-ff2577133186)
(2) Peer timeout
There are many peer connection timeout, such as "get sync message timeout" and "receive pong timeout". I know that the connections among nodes are not 100% stable, but it seems so frequently. I want to know whether it's because of the network setting of the nodes, or it's just normal and no need to worry about it.
![image](https://github.com/tronprotocol/java-tron/assets/16130943/df6f2322-c1fe-44c1-b2b0-f0b622cde86e)

I really appreciate your patience in answering my questions. Thanks!

**Comment by m-o-m12** [comment]
They are all normal logs, and will not affect node synchronization.

For CPU timeout warning, It is occurred when executing transactions, and It rely the status at that time and performance of the machine, So the transaction may be executed timeout at that time, but due to transaction retry mechanism, the timeout transaction will be re-executed, and most can be executed successfully. If it still fails, then error log like "Different result code" may be printed. and that will lead to the node stop synchronization.  So These warning logs you can ignore.

The same as Peer timeout warning log, they are normal logs when syncing block from others. If the block cannot be requested within the specified time, the connection will be disconnected.
