### ISSUE TITLE
get output like https://apilist.tronscanapi.com/api/transaction-info from fullNode

### ISSUE THREAD

**Issue by vahidsabet** [tronprotocol/java-tron#5294]
### System information
nohup java -Xms20G -Xmx59G -XX:ReservedCodeCacheSize=256m \
             -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m \
             -XX:MaxDirectMemorySize=1G -XX:+PrintGCDetails \
             -XX:+PrintGCDateStamps  -Xloggc:gc.log \
             -XX:+UseConcMarkSweepGC -XX:NewRatio=2 \
             -XX:+CMSScavengeBeforeRemark -XX:+ParallelRefProcEnabled \
             -XX:+HeapDumpOnOutOfMemoryError \
             -XX:+UseCMSInitiatingOccupancyOnly  -XX:CMSInitiatingOccupancyFraction=70 \
             -jar FullNode.jar -c main_net_config.conf --es >> start.log 2>&1 &

### 1. What did you do?

I want using my fullnode to retrieve data like:

https://apilist.tronscanapi.com/api/transaction-info?hash=[trx]

I have used mongo event plugin and also wallet/gettransactioninfobyid HTTP API but nothing have output like tronscan. How can I achieve to this.

### 2. What did you expect to see?

output of https://apilist.tronscanapi.com/api/transaction-info?hash=[trx]

### 3. What did you see instead?

some transaction info wont appear in the fullnode mongodb plugin

**Comment by m-o-m12** [comment]
@vahidsabet This Tronscan api [https://apilist.tronscanapi.com/api/transaction-info?hash=[trx]](https://apilist.tronscanapi.com/api/transaction-info?hash=%5Btrx%5D) returns the transaction info and transaction confirmation information, and all the data comes from the FullNode. And if you want to get the confirmation info from your node, just subscribe to solidified transactions or blocks is ok.  For Fullnode api, `wallet/gettransactionbyid` will return the transaction data, `wallet/gettransactioninfobyid` will return the transaction result data.

**Comment by vahidsabet** [comment]
Dear @m-o-m12 ,
Thanks for your response. But it didn't produce what I've looking for.
These functions don't include transaction info such as fromAddress, toAddress, isConfirmed, amount of asset and ...

**Comment by vahidsabet** [comment]
I've found transaction info by event subscribe using:
events/transaction/[Hash_ID]
but how can I check it has confirmed?

**Comment by m-o-m12** [comment]
@vahidsabet Just subscribe the solidified transactions is ok, and then node will sends the solidified transactions to the event plugin, and then the transactions will be stored into mongodb. Because all transactions are solidified data, so when using the event query service to query the transactions on mongo db, the return data is solidified.  

About how to only subscribe the solidified transactions, please refer to the guide: [configuration](https://github.com/tronprotocol/event-plugin#edit-configconf-of-java-tron-add-the-following-fileds ) and  [guide](https://developers.tron.network/docs/event-plugin-deployment-mongodb).
