### ISSUE TITLE
Firewall Rules (trusted ips)?

### ISSUE THREAD

**Issue by dewebdes** [tronprotocol/java-tron#5310]
Hi, I was go to setup a Full-Node(https://tronprotocol.github.io/documentation-en/developers/deployment/)...
I have some **failure & skipped** report in `./gradlew build` process.
Then I was **shutdown** my **firewall** and after that the build _complete with **no** fail or skip tests_!!!

Attacker IPS(based on my firewall rules):

- 172.104.166.147
- 179.43.163.133
- 78.47.119.245
- 45.148.10.241

So, I want to know that what is the white list IPs that I can make theme trusted?

**Comment by lurais** [comment]
@dewebdes As I can see, you build fullnode with firewall open, and it fails because the seed node in the config just propagates your node's ip to other nodes, that's why you find other ip's connecting to you. But your nodes only use the certain ports in the configuration file, so you can just add a certain port in the firewall instead of the IP because which nodes to connect to you are actually not sure.

**Comment by lurais** [comment]
@dewebdes Hello, can you provide relevant information? For example, jdk version, operating system version, code version used, etc. In addition, is there any detailed error messages during the build process ?
