### ISSUE TITLE
[Bounty] Java exeption caught, null Java heap space 

### ISSUE THREAD

**Issue by miimiispets** [tronprotocol/java-tron#541]
Please answer these questions before submitting your issue. Thanks!

What did you do?
I started full node using latest git commit v1.0.5

What did you expect to see?
I did not expect to see java exeption caught, null Java heap space

What did you see instead?
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AsyncAppender-Worker-ASYNC" and
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "nioEventLoopGroup-3-1"
![od v105 javalangoutofmemory](https://user-images.githubusercontent.com/38192052/39212798-09d0820c-4810-11e8-952a-b5fa7eb90d71.PNG)

**Comment by zhaohong** [comment]
@miimiispets   thanks you feedback.
when oom occur ,  what is the block num?

**Comment by miimiispets** [comment]
Hello Marcus. Is there a way to find it in a log?
Which log should contain this?
Would like to check so I can answer your question.

**Comment by miimiispets** [comment]
Possible work around found. Oom most likely caused by Gradle log causing full disk. I have a simple server with 40Gb hard drive. Manually removed Gradle log, freed up 80% disk space.
Restarted node. Will monitor functioning and report if exeption is reproduced again.

Using a server script to auto remove these logs every night. If succesful this specific exeption will not be thrown again.

**Comment by bondibox** [comment]
I just rebuilt my server and did a clean install. During sync it got to about block #18200 and started going really slowly, then stopped altogether with the following error:

> 20:32:09.285 ERROR [pool-5-thread-1] [o.t.c.n.n.NodeImpl](NodeImpl.java:422) Unhandled exception
> java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by miimiispets** [comment]
@bondibox What are your server specs?

**Comment by Rovak** [comment]
@miimiispets Logging can be configured in the https://github.com/tronprotocol/java-tron/blob/develop/src/main/resources/logback.xml file, right now the log is limited to 50GB, you can change it to a lower limit

@bondibox if you haven't already then you can increase the available memory for the java process by tweaking some jvm parameters. IIRC the default is 1/4th of your total available RAM, you can change this by adding the `-Xms256m -Xmx4096m` parameters. Set `-Xmx` to the max amount you want `java-tron` to use. This [stackoverflow](https://stackoverflow.com/questions/44701947/run-application-via-gradlew-with-xmx-and-xms) post shows a few ways to configure these parameters in gradle

**Comment by bondibox** [comment]
@miimiispets this is my testnet configuration. It's keeping up without dropping blocks, although I suspect this is only about 1% of the expected workload. 

Debian GNU/Linux 9.1 (stretch) 4.15.12-x86_64
 2500 MHz Intel(R) Celeron(R) M processor
 4	 	GB RAM  
 2 		CPU Cores  
 46 	GB SSD Storage  
 2256	SWAP

**Comment by zhaohong** [comment]
@huzhenyuan  follower this?

**Comment by miimiispets** [comment]
@Rovak Thanks! Will check what file size setting I currently have for that specific log. I changed the file size for /java-tron/src/main/resources/logback.xml. But this last one might not be the log being used during test net?
Also thanks for the stackoverflow post. Will read up on that one.

@bondibox Given your specs and running into oom I'm not sure I'll ever have my server running stable :D. But will keep trying nonetheless.

**Comment by jerkyrs** [comment]
OOM is not to do with drive full, the Linux kernel will kill a process if the server is out of memory, it will sacrifice one it thinks is less important.

A java heap space is caused by the process attempting to do something which requires more memory then is allocated to the JVM. As per comments above you should pass this into your JVM

`-Xms256m -Xmx4096m`

You can not or should not allocate more memory to your user space then your available memory,  if you have a machine with 16GB of memory and you are only running java-tron on it you should not allocate more then 8192m  (to be conservative) as the OS will handle other operations that require memory

The startup java-tron should be documented to include passing memory arguments. There is a script laying around somewhere (pretty basic) but this is what it could look like

`#!/bin/bash
kill -9 `cat /home/tron/pid.txt`
killall -9 java
nohup  java -Xms256m -Xmx4096m -jar /home/tron/java-tron/build/libs/java-tron.jar -p $LOCAL_WITNESS_PRIVATE_KEY --witness -c /home/tron/config.conf > /home/tron/tron-shell.log 2>&1 & echo $! >/home/tron/pid.txt`

**Comment by zhaohong** [comment]
@wind4869  to provide a startup script.
