### ISSUE TITLE
Can we change the decimal places in tron private chain native currency?

### ISSUE THREAD

**Issue by SukiratWarring** [tronprotocol/java-tron#5628]

**Comment by m-o-m12** [comment]
@SukiratWarring You can change the java-tron code to modidy the decimals of native currency, then compile and build it. Modify the value of TRX_PRECISION: https://github.com/tronprotocol/java-tron/blob/develop/common/src/main/java/org/tron/core/config/Parameter.java#L77

**Comment by SukiratWarring** [comment]
@m-o-m12 I tried changing the constant to 10_000_000L , making a build and then running it but I don't see any change do we have to change anything else?

**Comment by m-o-m12** [comment]
@SukiratWarring No other changes except the TRX_PRECISION. In fact it is hard to see any difference after changing the decimals, because the data on chain is represented as integer, and there is no broswer for private chain, so only from the accout balance returned by node API, it's hard to get the difference.

**Comment by SukiratWarring** [comment]
@m-o-m12 the above issue is something i am trying to resolve can you see to it!
