### ISSUE TITLE
broadcast order

### ISSUE THREAD

**Issue by 19byte** [tronprotocol/java-tron#5682]
![telegram-cloud-photo-size-1-4990511162412084267-y](https://github.com/tronprotocol/java-tron/assets/87568744/799c50ae-e31f-4282-84b4-9a2fa715ddbd)

sometimes I delegate first and then reclaim. How can I ensure that the broadcast order is consistent with what I wrote in my code?

**Comment by laurenceja** [comment]
@19byte If two transactions are broadcasted at the same time, or the broadcast times are very close, due to the machine or network status at that time, we cannot guarantee which one will be executed first.

If you use a certain fullnode, after sending the first transaction, just sending the second transaction after some time, for example, 1 second. This basically guarantees the execution order of transactions.

If the execution order of transactions must be guaranteed, it is better to query the first transaction before sending the second transaction. The interval also only needs several seconds.

**Comment by 19byte** [comment]
@laurenceja okay, I know
