### ISSUE TITLE
广播成功的转账消失了

### ISSUE THREAD

**Issue by ejdbc** [tronprotocol/java-tron#5848]
txId: efcf0b9832323430e50f75d666f9f619ab37ccf291372efeff85ba42033bdf23 

这个转账广播成功，节点日志提示广播出去了，但是现在查不到这个转账的任何信息，这个可能是bug吗？

节点日志：09:29:54.154 INFO  [qtp1939597292-104920] [o.t.c.Wallet](Wallet.java:559) Broadcast transaction efcf0b9832323430e50f75d666f9f619ab37ccf291372efeff85ba42033bdf23 to 28 peers successfully.

**Comment by endiaoekoe** [comment]
> Broadcast transaction

could you provide more logs about the missing tx so that it can be investigated more clearly?
btw, you can refer to [issue1 ](https://github.com/tronprotocol/java-tron/issues/5627) / [issue2 ](https://github.com/tronprotocol/java-tron/issues/5607) which may be very similar with your issue mentioned above.

**Comment by halibobo1205** [comment]
"broadcast was successful" means this transaction is validated by this full node, but it doesn't mean that it can be accepted by other sr,  you can find more details here https://github.com/tronprotocol/java-tron/issues/5749#issuecomment-1984991010.

**Comment by vivian1912** [comment]
@ejdbc Does this answer your question? This issue will be closed as no update for a long time. Please feel free to re-open it if you still have any questions, thanks.
