### ISSUE TITLE
Website login issues - growing number of user complaints

### ISSUE THREAD

**Issue by perogiesredditmod** [tronprotocol/java-tron#750]
Hi, perogies here, /r/tronix moderator.  We have been receiving a steady stream of reports from users for the past month about not being able to login to their accounts on tron.network

Unfortunately a lot of these users have deposited their TRX in the wallet on the Tron website.  The number of complaints is rising.  These people need to be able to access those funds or we're going to have a big problem with backlash. 

I'd like to be able to contact your team more directly, but reaching out to you so far has yielded zero results.

**Comment by techno420** [comment]
Hello,
I got login problems too.
My problem is that it always says "mailbox or password error" which cant be because my details are saved in my samsung pass.
After several attempts i tried to reset my password, but the link in the e-mail you get redirect me to the tron home(main)page where theres no field to reset the password.
I hope these informations help you fix the bug

**Comment by techno420** [comment]
I made screenshoots but i dont know how to add them on github

**Comment by a49688448** [comment]
@techno420 
Thank you!
we'll fix the two bugs today.

**Comment by techno420** [comment]
Thank you
