### ISSUE TITLE
Testnet version INCOMPATIBLE_PROTOCOL

### ISSUE THREAD

**Issue by jerkyrs** [tronprotocol/java-tron#777]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Pulled out master and tried to connect to testnet with default config.conf

2. What did you expect to see?
Connections to other nodes but there are variety of other incompatibles nodes

3. What did you see instead?
`14:16:03.633 INFO  [nioEventLoopGroup-3-10] [HandshakeHandler](HandshakeHandler.java:121) Peer /80.29.83.2:22475 different p2p version, peer->46, me->64
14:16:03.633 INFO  [nioEventLoopGroup-3-10] [Channel](Channel.java:149) Send disconnect to /80.29.83.2:22475, reason:INCOMPATIBLE_PROTOCOL
14:16:03.633 INFO  [nioEventLoopGroup-3-10] [TronChannelInitializer](TronChannelInitializer.java:85) Close channel:/80.29.83.2:22475 | c367cb6bc21f56716b5a50eb12b98a499276d7eb3f8af48b46a1b8b82b7b5c2f9c5e05df1fb399e9ee701b80a3ce0e268a0bec798eea58f0e820fb7fc8253961`

Not sure if this is connecting to other nodes or not but my protocol version seems to be 64 which seems to be defined on config.conf

  p2p {
    version = 64 # 64: testnet; 101: debug
  }

**Comment by pynki** [comment]
[config.conf](https://github.com/tronprotocol/java-tron/blob/develop/src/main/resources/config.conf) defines 
p2p {
    version = 67 # 67: testnet; 101: debug
}
 right now. 

Consider pulling the repo again because the genesis.block change too2 days ago as far i could see. I ran into a bunch of INCOMPATIBLE_CHAIN errors when connecting to [34rth's](https://tron.34rth.com/) [private testnet](https://github.com/34rth/tron)

**Comment by wubin12** [comment]
it is caused by different version
