### ISSUE TITLE
Trouble with linux builds

### ISSUE THREAD

**Issue by bondibox** [tronprotocol/java-tron#788]
Please follow this issue
https://github.com/gradle/gradle-native/issues/684

> I am working with tronprotocol/java-tron master branch. It specifies JDK8 which I am using. Every few days I will delete ~/.gradle and reclone the repo. Once in a while it won't build, with failed tests. Meanwhile the same process builds fine on my mac. I have tried new Debian builds and the recommended Ubuntu but it is not a problem specific to the distribution or linux build.

**Comment by jerkyrs** [comment]
They need to implement proper branching model, if they used git-flow and only merged from a release branch into master rather than direct commits to master then builds should always work in master branch. There are a number of commits directly to master.

https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by bondibox** [comment]
I'm not sure who you are referring to by "they" because both repos are guilty of committing to master.

Just to be clear, I am confident that the problem lies with gradle constant commits that haven't been cross platform tested. Java-tron commits that used to build are now failing and will until next commit (fingers crossed). I think the answer is to freeze to a gradle commit that works so we're not at the metcy of their untested commits.

**Comment by bondibox** [comment]
Well I was wrong. I got a chance to look closer and java-tron IS frozen to gradle 4.3, but it in turn pulls down nearly 300 libraries.
